### ISSUE TITLE
Bug: you can accidentally trigger insert mode and not get out

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#24]
**Problem**
Accidentally entered insert mode for a text element without realising because I thought I had a different window focused (a regular occurence). 

Changed to the other window to type what I needed to type, switched back to Utopia and now I can't exit Insert mode (via pressing esc or trying to complete an insertion - had to reload the editor!) because:

```
    Error: Unable to use insert drag state in select mode.
        at https://utopia.app/editor/1.7e88d1d90dfe917165b7.js:1:213797
        at Object.s [as foldEither] (https://utopia.app/editor/1.7e88d1d90dfe917165b7.js:1:82441)
        at Object.z [as produceCanvasTransientState] (https://utopia.app/editor/1.7e88d1d90dfe917165b7.js:1:211778)
        at https://utopia.app/editor/editor.40d79b3703ee256b79c4.js:1:1033446
        at t.reduce.reduce (https://utopia.app/editor/editor.40d79b3703ee256b79c4.js:1:1035902)
        at Array.reduce (<anonymous>)
        at Object.CEmK.n.editorDispatch (https://utopia.app/editor/editor.40d79b3703ee256b79c4.js:1:1032947)
        at n (https://utopia.app/editor/editor.40d79b3703ee256b79c4.js:1:1660135)
        at n.Editor.dispatch (https://utopia.app/editor/editor.40d79b3703ee256b79c4.js:1:1660269)
```

**Comment by maltenuhn** [comment]
Closing as this has been fixed by [insert ticket number]
